#!/usr/bin/env bash

mkdir "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1"
mv "./Commedians in Cars Getting Coffee/S01E01 - Larry Eats a Pancake - Larry David.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E02 - Mad Man in a Death Machine - Ricky Gervais .mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E03 - A Monkey and a Lava Lamp - Brian Regan.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E04 - Just a Lazy Shiftless Bastard - Alec Baldwin.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E05 - A Taste of Hell From on High - Joel Hodgson.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E06 - Unusable on the Internet - Bob Einstein.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E07 - You Don't Want to Offend a Cannibal.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E08 - I Hear Downtown Abbey is Pretty Good... - Colin Quinn & Mario Joyner.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E09 - I want Sandwishes, I want Chicken - Carl Reiner & Mel Brooks.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mv "./Commedians in Cars Getting Coffee/S01E10 - It's Bubbly Time, Jerry - Micheal Richards.mp4" "./Commedians in Cars Getting Coffee/Commedians in Cars Getting Coffee - Season 1/"
mkdir "./Community/Community - Season 2"
mv "./Community/Community.S02E04.HDTV.XviD-LOL.avi" "./Community/Community - Season 2/"
mkdir "./Futurama/Futurama - Season 6"
mv "./Futurama/Futurama.S06E10.The.Prisoner.of.Benda.HDTV.XviD-FQM.avi" "./Futurama/Futurama - Season 6/"
mkdir "./It's Always Sunny in Philadelphia/IASIP - Season 6"
mv "./It's Always Sunny in Philadelphia/Its.Always.Sunny.in.Philadelphia.S06E05.HDTV.XviD-P0W4.avi" "./It's Always Sunny in Philadelphia/It's Always Sunny in Philadelphia - Season 6/"
mkdir "./Modern Family/Modern Family - Season 5"
mv "./Modern Family/Modern.Family.S05E01.HDTV.x264-LOL.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E02.HDTV.x264-LOL.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E03.HDTV.x264-LOL.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E04.HDTV.x264-2HD.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E05.HDTV.x264-LOL.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E06.HDTV.x264-ASAP.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E07.HDTV.x264-2HD.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E09.HDTV.x264-KILLERS.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E10.HDTV.x264-KILLERS.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E11.PROPER.HDTV.x264-KILLERS.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E12.HDTV.x264-EXCELLENCE.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E13.HDTV.x264-EXCELLENCE.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E14.HDTV.x264-EXCELLENCE.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E15.HDTV.x264-KILLERS.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E16.HDTV.x264-EXCELLENCE.mp4" "./Modern Family/Modern Family - Season 5/"
mv "./Modern Family/Modern.Family.S05E17.HDTV.x264-2HD.mp4" "./Modern Family/Modern Family - Season 5/"
mkdir "./Simpsons/Simpsons - Season 21"
mv "./Simpsons/The.Simpsons.S21E01.Homer.the.Whopper.HDTV.XviD-FQM.avi" "./Simpsons/Simpsons - Season 21/"
mkdir "./South Park/South Park - Season 12"
mv "./South Park/South.Park.S12E07.REPACK.DSR.XviD-0TV.avi" "./South Park/South Park - Season 12/"
mkdir "./South Park/South Park - Season 14"
mv "./South Park/South.Park.S14E09.Its.a.Jersey.Thing.HDTV.XviD-FQM.avi" "./South Park/South Park - Season 14/"
mv "./South Park/South.Park.S14E10.Insheeption.HDTV.XviD-FQM.avi" "./South Park/South Park - Season 14/"
mkdir "./The Sopranos/The Sopranos - Season 1"
mv "./The Sopranos/The Sopranos - S01E01 - Pilot.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E02 - 46 Long.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E03 - Denial, Anger, Acceptance.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E04 - Meadowlands.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E05 - College.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E06 - Pax Soprana.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E07 - Down Neck.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E08 - The Legend of Tennessee Moltisanti.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E09 - Boca.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E10 - A Hit Is a Hit.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E11 - Nobody Knows Anything.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E12 - Isabella.avi" "./The Sopranos/The Sopranos - Season 1/"
mv "./The Sopranos/The Sopranos - S01E13 - I Dream of Jeannie Cusamano.avi" "./The Sopranos/The Sopranos - Season 1/"
mkdir "./Workaholics/Workaholics - Season 3"
mv "./Workaholics/Workaholics.S03E12.REPACK.HDTV.x264-2HD.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E13.HDTV.x264-2HD.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E14.HDTV.x264-2HD.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E15.Webcam.Girl.HDTV.x264-FQM.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E16.HDTV.x264-ASAP.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E17.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E18.HDTV.x264-2HD.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E19.HDTV.x264-EVOLVE.mp4" "./Workaholics/Workaholics - Season 3/"
mv "./Workaholics/Workaholics.S03E20.HDTV.x264-EVOLVE.mp4" "./Workaholics/Workaholics - Season 3/"
mkdir "./Workaholics/Workaholics - Season 4"
mv "./Workaholics/Workaholics.S04E01.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E02.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E03.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E04.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E05.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E06.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E07.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
mv "./Workaholics/Workaholics.S04E08.HDTV.x264-EXCELLENCE.mp4" "./Workaholics/Workaholics - Season 4/"
